# pub.dev using `flutter pub publish`

name: clipped_shapes
description: Container widgets with a shaped border that crops the content and keeps the touch feedback on the foreground.
repository: https://github.com/gary6lin/clipped_shapes
version: 1.0.0

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - button
  - border
  - shape
  - clip
  - box